//============================================================
// TB B16 — 16×16 Systolic Array Verification
//============================================================
// Verifies:
//   1. Reset clears all state
//   2. Weight loading works
//   3. Identity matrix: A × I = A
//   4. All-ones matrix: known expected result
//   5. Dense random matrix: RTL vs NumPy golden model
//   6. No X/Z values
//   7. Full scoreboard with PASS/FAIL
//
// Test vectors loaded from .mem files generated by:
//   python/golden_model/matmul_reference.py
//
// Clock: 500 MHz (2ns period)
//============================================================

`timescale 1ns/1ps

module tb_b16;

    //----------------------------------------------------------
    // Parameters
    //----------------------------------------------------------

    localparam N = 16;
    localparam TOTAL_CYCLES = N + N - 1 + 3; // 34

    //----------------------------------------------------------
    // DUT Signals
    //----------------------------------------------------------

    logic                  clk;
    logic                  rst_n;

    logic                  load_weight;
    logic [3:0]            weight_row_sel;
    logic signed [7:0]     weight_in [0:N-1];

    logic                  start;
    logic signed [7:0]     act_in    [0:N-1];

    logic                  done;
    logic signed [31:0]    result    [0:N-1][0:N-1];

    //----------------------------------------------------------
    // Test Vector Memories
    //----------------------------------------------------------

    logic signed [7:0]     A_mem     [0:N*N-1];
    logic signed [7:0]     B_mem     [0:N*N-1];
    logic signed [31:0]    C_expected[0:N*N-1];

    //----------------------------------------------------------
    // DUT Instantiation
    //----------------------------------------------------------

    systolic16x16_baseline dut
    (
        .clk            (clk),
        .rst_n          (rst_n),

        .load_weight    (load_weight),
        .weight_row_sel (weight_row_sel),
        .weight_in      (weight_in),

        .start          (start),
        .act_in         (act_in),

        .done           (done),
        .result         (result)
    );

    //----------------------------------------------------------
    // Clock — 500 MHz
    //----------------------------------------------------------

    initial
    begin
        clk = 1'b0;
        forever #1 clk = ~clk;
    end

    //----------------------------------------------------------
    // Scoreboard
    //----------------------------------------------------------

    integer total_pass;
    integer total_fail;
    integer test_pass;
    integer test_fail;

    //----------------------------------------------------------
    // Reset Task
    //----------------------------------------------------------

    task automatic reset_dut;
    begin

        rst_n        = 1'b0;
        load_weight  = 1'b0;
        weight_row_sel = '0;
        start        = 1'b0;

        for (int i = 0; i < N; i++)
        begin
            weight_in[i] = '0;
            act_in[i]    = '0;
        end

        repeat(5) @(posedge clk);

        rst_n = 1'b1;

        repeat(2) @(posedge clk);

    end
    endtask

    //----------------------------------------------------------
    // Load Weights from Memory
    // B_mem[k*N + j] = B[k][j]
    //----------------------------------------------------------

    task automatic load_weights_from_mem;
    begin

        for (int row = 0; row < N; row++)
        begin
            @(posedge clk);

            load_weight    <= 1'b1;
            weight_row_sel <= row[3:0];

            for (int col = 0; col < N; col++)
                weight_in[col] <= B_mem[row * N + col];
        end

        @(posedge clk);
        load_weight <= 1'b0;

        repeat(2) @(posedge clk);

    end
    endtask

    //----------------------------------------------------------
    // Load Weights from Array
    //----------------------------------------------------------

    task automatic load_weights_array(
        input logic signed [7:0] W [0:N*N-1]
    );
    begin

        for (int row = 0; row < N; row++)
        begin
            @(posedge clk);

            load_weight    <= 1'b1;
            weight_row_sel <= row[3:0];

            for (int col = 0; col < N; col++)
                weight_in[col] <= W[row * N + col];
        end

        @(posedge clk);
        load_weight <= 1'b0;

        repeat(2) @(posedge clk);

    end
    endtask

    //----------------------------------------------------------
    // Stream Activations
    // A_mem[i*N + k] = A[i][k]
    // At cycle i: act_in[k] = A[i][k]
    //----------------------------------------------------------

    task automatic stream_activations_from_mem;
    begin

        @(posedge clk);
        start <= 1'b1;

        for (int i = 0; i < N; i++)
        begin
            for (int k = 0; k < N; k++)
                act_in[k] <= A_mem[i * N + k];

            @(posedge clk);

            if (i == 0)
                start <= 1'b0;
        end

        // Clear inputs
        for (int k = 0; k < N; k++)
            act_in[k] <= '0;

    end
    endtask

    //----------------------------------------------------------
    // Stream Activations from Array
    //----------------------------------------------------------

    task automatic stream_activations_array(
        input logic signed [7:0] A [0:N*N-1]
    );
    begin

        @(posedge clk);
        start <= 1'b1;

        for (int i = 0; i < N; i++)
        begin
            for (int k = 0; k < N; k++)
                act_in[k] <= A[i * N + k];

            @(posedge clk);

            if (i == 0)
                start <= 1'b0;
        end

        for (int k = 0; k < N; k++)
            act_in[k] <= '0;

    end
    endtask

    //----------------------------------------------------------
    // Check Results Against Expected
    //----------------------------------------------------------

    task automatic check_results_mem(
        input string test_name
    );
    begin

        test_pass = 0;
        test_fail = 0;

        for (int i = 0; i < N; i++)
        begin
            for (int j = 0; j < N; j++)
            begin
                if (result[i][j] === C_expected[i * N + j])
                begin
                    test_pass++;
                    total_pass++;
                end
                else
                begin
                    test_fail++;
                    total_fail++;

                    $display(
                        "[FAIL] %s: C[%0d][%0d] expected=%0d got=%0d",
                        test_name, i, j,
                        C_expected[i * N + j],
                        result[i][j]);
                end
            end
        end

        $display("[%s] %s: %0d/%0d passed",
            (test_fail == 0) ? "PASS" : "FAIL",
            test_name,
            test_pass,
            test_pass + test_fail);

    end
    endtask

    //----------------------------------------------------------
    // Check Results Against Array
    //----------------------------------------------------------

    task automatic check_results_array(
        input string test_name,
        input logic signed [31:0] C_exp [0:N*N-1]
    );
    begin

        test_pass = 0;
        test_fail = 0;

        for (int i = 0; i < N; i++)
        begin
            for (int j = 0; j < N; j++)
            begin
                if (result[i][j] === C_exp[i * N + j])
                begin
                    test_pass++;
                    total_pass++;
                end
                else
                begin
                    test_fail++;
                    total_fail++;

                    $display(
                        "[FAIL] %s: C[%0d][%0d] expected=%0d got=%0d",
                        test_name, i, j,
                        C_exp[i * N + j],
                        result[i][j]);
                end
            end
        end

        $display("[%s] %s: %0d/%0d passed",
            (test_fail == 0) ? "PASS" : "FAIL",
            test_name,
            test_pass,
            test_pass + test_fail);

    end
    endtask

    //----------------------------------------------------------
    // X Detection
    //----------------------------------------------------------

    always @(posedge clk)
    begin
        if (done)
        begin
            for (int i = 0; i < N; i++)
            begin
                for (int j = 0; j < N; j++)
                begin
                    if (^result[i][j] === 1'bx)
                    begin
                        $error("X detected at result[%0d][%0d]", i, j);
                        $finish;
                    end
                end
            end
        end
    end

    //----------------------------------------------------------
    // Main Test Sequence
    //----------------------------------------------------------

    // Test data arrays for identity and ones tests
    logic signed [7:0]  test_A [0:N*N-1];
    logic signed [7:0]  test_B [0:N*N-1];
    logic signed [31:0] test_C [0:N*N-1];

    initial
    begin

        total_pass = 0;
        total_fail = 0;

        $display("");
        $display("================================================");
        $display(" B16 SYSTOLIC ARRAY VERIFICATION START");
        $display("================================================");
        $display("");

        reset_dut();

        //------------------------------------------------------
        // Test 1: Identity Matrix
        // A × I = A (but with INT32 result, so C[i][j] = A[i][j])
        //------------------------------------------------------

        $display("");
        $display("--- Test 1: Identity Matrix ---");

        // Generate A = small known values, B = identity
        for (int i = 0; i < N; i++)
        begin
            for (int j = 0; j < N; j++)
            begin
                test_A[i * N + j] = (i * N + j + 1);  // 1..256 truncated to int8
                test_B[i * N + j] = (i == j) ? 8'sd1 : 8'sd0;
                // C = A × I = A
                test_C[i * N + j] = 32'(signed'(test_A[i * N + j]));
            end
        end

        // Wait — A values > 127 will overflow INT8. Use modular values
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                test_A[i * N + j] = ((i * N + j) % 256) - 128; // Range -128..127

        // Recompute C = A × I = A
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                test_C[i * N + j] = 32'(signed'(test_A[i * N + j]));

        load_weights_array(test_B);
        stream_activations_array(test_A);

        wait(done);
        @(posedge clk);

        check_results_array("Identity", test_C);

        reset_dut();

        //------------------------------------------------------
        // Test 2: All-Ones Matrix
        // A = all 1s, B = all 1s
        // C[i][j] = N (each element = sum of 16 ones = 16)
        //------------------------------------------------------

        $display("");
        $display("--- Test 2: All-Ones Matrix ---");

        for (int i = 0; i < N * N; i++)
        begin
            test_A[i] = 8'sd1;
            test_B[i] = 8'sd1;
            test_C[i] = 32'sd16;  // 1*1 summed 16 times
        end

        load_weights_array(test_B);
        stream_activations_array(test_A);

        wait(done);
        @(posedge clk);

        check_results_array("All-Ones", test_C);

        reset_dut();

        //------------------------------------------------------
        // Test 3: Dense Random (from Python golden model)
        //------------------------------------------------------

        $display("");
        $display("--- Test 3: Dense Random (Golden Model) ---");

        $readmemh("vectors/dense/A_matrix.mem", A_mem);
        $readmemh("vectors/dense/B_matrix.mem", B_mem);
        $readmemh("vectors/dense/C_expected.mem", C_expected);

        load_weights_from_mem();
        stream_activations_from_mem();

        wait(done);
        @(posedge clk);

        check_results_mem("Dense-Random");

        reset_dut();

        //------------------------------------------------------
        // Test 4: Negative values test
        // A = all -1, B = all 1s
        // C[i][j] = -16
        //------------------------------------------------------

        $display("");
        $display("--- Test 4: Negative Values ---");

        for (int i = 0; i < N * N; i++)
        begin
            test_A[i] = -8'sd1;
            test_B[i] =  8'sd1;
            test_C[i] = -32'sd16;
        end

        load_weights_array(test_B);
        stream_activations_array(test_A);

        wait(done);
        @(posedge clk);

        check_results_array("Negative", test_C);

        //------------------------------------------------------
        // Final Summary
        //------------------------------------------------------

        $display("");
        $display("================================================");
        $display(" TOTAL PASS = %0d", total_pass);
        $display(" TOTAL FAIL = %0d", total_fail);
        $display("================================================");
        $display("");

        if (total_fail == 0)
            $display("B16_TEST PASSED");
        else
            $display("B16_TEST FAILED");

        $finish;

    end

    //----------------------------------------------------------
    // Waveform Dump
    //----------------------------------------------------------

    initial
    begin

        $dumpfile("tb_b16.vcd");

        $dumpvars(0, tb_b16);

    end

endmodule
